version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cinch-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cinch
      POSTGRES_USER: cinch
      POSTGRES_PASSWORD: cinchtest
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: cinch-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata: